Migrate to Enterprise Linux 8 (#65)
Images:
* Fix building OpenSSL
* Install CMake, Git and ccache from distribution
 - ccache is from epel, and needs to be installed after it
* Document EL8 migration
* fix pushing images by getting the labels right
* use multiple targets rather than env vars in makefile

CI:
* enable multi-arch docker
* don’t truncate docker logs
* parallelize GHA CI
* drop schedule
* merge edge & pr jobs
* upload artifacts rather than publish to ghcr

---------

Co-authored-by: Hongli Lai <hongli@hongli.nl>

diff --git a/.github/workflows/dockerimage-ci.yml b/.github/workflows/dockerimage-ci.yml
--- a/.github/workflows/dockerimage-ci.yml
+++ b/.github/workflows/dockerimage-ci.yml
@@ -3,8 +3,6 @@ name: Docker Image CI
 on:
   create:
   workflow_dispatch:
-  schedule:
-    - cron: '15 05 * * 1' # Late night for the Americas, early morning for Europe
   pull_request:
     paths-ignore:
       - '**.md'
@@ -24,8 +22,8 @@ jobs:
     name: Code checks
     runs-on: ubuntu-20.04
     steps:
-      - uses: actions/checkout@v2
-      - uses: ludeeus/action-shellcheck@94e0aab03ca135d11a35e5bfc14e6746dc56e7e9
+      - uses: actions/checkout@v4
+      - uses: ludeeus/action-shellcheck@2.0.0
         env:
           SHELLCHECK_OPTS: -x
       - name: Install eclint
@@ -35,68 +33,84 @@ jobs:
 
   build_pr:
     name: "Test Build Docker images"
-    if: github.event_name == 'pull_request' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
+    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || ( github.event_name != 'create' && github.event_name != 'pull_request' && github.event_name != 'schedule' )
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        arch:
+          - 'amd64'
+          - 'arm64'
+    env:
+      OWNER: '${{ github.repository_owner }}'
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v4
     - name: Set lower case repository owner name
-      run: |
-        echo "OWNER_LC=${OWNER,,}" >>"$GITHUB_ENV"
-      env:
-        OWNER: '${{ github.repository_owner }}'
-    - name: Build the Docker images
-      run: make DISABLE_OPTIMIZATIONS=1 "OWNER=$OWNER_LC"
-
-  build_edge:
-    name: "Build edge Docker images"
-    if: github.event_name != 'create' && github.event_name != 'pull_request' && github.event_name != 'schedule'
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v2
-    - name: Set lower case repository owner name
-      run: |
-        echo "OWNER_LC=${OWNER,,}" >>"$GITHUB_ENV"
-      env:
-        OWNER: '${{ github.repository_owner }}'
+      run: echo "OWNER_LC=${OWNER,,}" >> "$GITHUB_ENV"
     - name: Log in to the Container registry
-      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
+      uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
+    - name: Enable docker multiarch
+      uses: docker/setup-qemu-action@v3
+    - name: Fix docker logs
+      uses: docker/setup-buildx-action@v3
+      with:
+        driver-opts: |
+          env.BUILDKIT_STEP_LOG_MAX_SIZE=-1
+          env.BUILDKIT_STEP_LOG_MAX_SPEED=-1
+          default-load=true
     - name: Build the Docker images
-      run: make "OWNER=$OWNER_LC" VERSION=edge
-    - name: Push the Docker images
-      run: docker push "ghcr.io/$OWNER_LC/holy-build-box:edge"
+      run: make DISABLE_OPTIMIZATIONS=1 "OWNER=$OWNER_LC" build_${{matrix.arch}}
+    - name: Export image
+      run: make "OWNER=$OWNER_LC" export_${{matrix.arch}}
+    - name: Upload artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: docker_image_${{matrix.arch}}
+        path: hbb_*.tar
 
   build_release:
     name: "Build release Docker images"
     if: github.event_name == 'create' && github.event.ref_type == 'tag'
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        arch:
+          - 'amd64'
+          - 'arm64'
+    env:
+      TAG: ${{ github.event.ref }}
+      OWNER: '${{ github.repository_owner }}'
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v4
     - name: Set lower case repository owner name
+      run: echo "OWNER_LC=${OWNER,,}" >> "$GITHUB_ENV"
+    - name: Check versions match (Makefile & git-tag)
       run: |
-        echo "OWNER_LC=${OWNER,,}" >>"$GITHUB_ENV"
-      env:
-        OWNER: '${{ github.repository_owner }}'
-    - name: Check tag
-      run: |
-        VERSION1=$(grep '^VERSION = ' Makefile | sed 's|.*= *||')
-        VERSION2=$(sed 's|^rel-||' <<< "$TAG")
-        if [[ "$VERSION1" != "$VERSION2" ]]; then
-          echo "ERROR: version in Makefile ($VERSION1) doesn't match Git tag ($VERSION2)"
+        MAKEFILE_VERSION=$(grep '^VERSION = ' Makefile | sed 's|.*= *||')
+        GIT_TAG_VERSION=$(sed 's|^rel-||' <<< "$TAG")
+        if [[ "MAKEFILE_$VERSION" != "$GIT_TAG_VERSION" ]]; then
+          echo "ERROR: version in Makefile ($MAKEFILE_VERSION) doesn't match Git tag ($GIT_TAG_VERSION)"
           exit 1
         fi
-      env:
-        TAG: ${{ github.event.ref }}
     - name: Log in to the Container registry
-      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
+      uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
+    - name: Enable docker multiarch
+      uses: docker/setup-qemu-action@v3
+    - name: Fix docker logs
+      uses: docker/setup-buildx-action@v3
+      with:
+        driver-opts: |
+          env.BUILDKIT_STEP_LOG_MAX_SIZE=-1
+          env.BUILDKIT_STEP_LOG_MAX_SPEED=-1
+          default-load=true
     - name: Build the Docker images
-      run: make build "OWNER=$OWNER_LC"
+      run: make "OWNER=$OWNER_LC" build_${{matrix.arch}}
     - name: Tag and push the Docker images
-      run: make release "OWNER=$OWNER_LC"
+      run: make "OWNER=$OWNER_LC" release
